### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by kekko7072** [GizmosDev/gizmos_settings_screen#1]
Hey this package is great. I'd like to use it on my app, can you add null safety support?

**Comment by DaveWoodCom** [comment]
Yes, on my list, just need the time to get to it.

**Comment by kekko7072** [comment]
> Yes, on my list, just need the time to get to it.

Thank you so much I really love this library, I can't wait to start using it. When you have uploaded close this topic so i will start using it

**Comment by DaveWoodCom** [comment]
Done. Let me know if you see any issues.

**Comment by kekko7072** [comment]
Thank you 🙏
